# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sugar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Record.date'),
            preserve_default=False,
        ),
    ]
